---

# old way
#- name: 'copy R sources and unarchive in tmp "
#  unarchive:
#      src: R-{{rversion}}.tar.gz
#      dest: /tmp 
      

- name: get and copy R sources in tmp
  get_url: 
    url: "https://cran.r-project.org/src/base/R-3/R-{{rversion}}.tar.gz"
    dest: /tmp
    
   
- name: unarchive previous file in tmp
  unarchive:
    src: "/tmp/R-{{rversion}}.tar.gz"
    dest: /tmp 
    remote_src: yes
      
- 
  name: configure R
  command: ./configure --prefix=/opt/R/{{rversion}} --enable-R-shlib --with-blas --with-lapack
    chdir="/tmp/R-{{rversion}}"
    
- 
  name: compile  R
  make: 
    chdir: "/tmp/R-{{rversion}}"
  become: yes
    
- 
  name: install  R
  make:  
    target: install 
    chdir: "/tmp/R-{{rversion}}"
     
-
  name: suppressing  R tar.gz
  file: 
    name: "/tmp/R-{{rversion}}.tar.gz"
    state: absent
    
-
  name: suppressing  R sources
  file: 
    name: "/tmp/R-{{rversion}}"
    state: absent
