---

# phase d'installation de RStudio server pro
# src : https://www.rstudio.com/products/rstudio/download-server/
# src : https://support.rstudio.com/hc/en-us/articles/234653607-Getting-Started-with-RStudio-Server
# src : https://support.rstudio.com/hc/en-us/articles/212364537-Using-multiple-versions-of-R-with-RStudio-Server-Pro


- debug:
    msg: "Début de l'installation du package {{rstudio_file}}"
    
# old way
#- name: 'copy Rstudio rpm  in tmp  get_url https://download2.rstudio.org/rstudio-server-rhel-pro-1.1.456-x86_64.rpm'
#  copy:
#    src: '{{rstudio_file}}.rpm'
#    dest: /tmp


- name: get and copy RStudio rpm in tmp
  get_url: 
    url: "https://download2.rstudio.org/{{rstudio_file}}.rpm"
    dest: /tmp
    
    
- name: uninstall previous RStudio install
  yum:
    name: rstudio-server
    state: absent
    
- name: install RStudio
  yum:
    name: "/tmp/{{ rstudio_file }}.rpm"
    state: present
    
- name: delete RStudio rpm file
  file:
    name: /tmp/{{ rstudio_file }}.rpm
    state: absent